# Generated by Django 4.1 on 2025-09-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_options_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Учетную запись', 'verbose_name_plural': 'Учетные записи'},
        ),
    ]
